# docker-compose.yml - FOR LOCAL DEVELOPMENT ONLY
# Oracle Cloud uses single container deployment

services:
  postgres:
    image: kartoza/postgis:16-3.4
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  inference:
    build:
      context: .
    environment:
      - AWS_NO_SIGN_REQUEST=true
      - AWS_S3_ENDPOINT=s3.af-south-1.amazonaws.com
    depends_on:
      - postgres
    ports:
      - "8501:8501"
    command: >
      streamlit run app.py
      --server.address=0.0.0.0
      --server.port=8501

  checkdb:
    image: schaffdev/port_check:latest
    environment:
      - CHECK_HOST=postgres
      - CHECK_PORT=5432
    depends_on:
      - postgres
