services:
  postgres:
    image: kartoza/postgis:16-3.4
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  inference:
    build:
      context: .
    volumes:
      - ./datacube.conf:/opt/app/datacube.conf:ro
    environment:
      - DATACUBE_CONFIG_PATH=/opt/app/datacube.conf
      - AWS_NO_SIGN_REQUEST=true
      - AWS_S3_ENDPOINT=s3.af-south-1.amazonaws.com
      # datacube will pick these up (or can write them into .datacube.conf)
      # - DATACUBE_CONFIG_PATH=/opt/app/.datacube.conf
    depends_on:
      - postgres
    ports:
      - "8501:8501"
    command: >
      streamlit run app.py
      --server.address=0.0.0.0
      --server.port=8501


#  jupyter:
#    build: .
#    environment:
#      - DB_HOSTNAME=postgres
#      - DB_USERNAME=opendatacube
#      - DB_PASSWORD=opendatacubepassword
#      - DB_DATABASE=opendatacube
#      - AWS_NO_SIGN_REQUEST=true
#      - AWS_S3_ENDPOINT=s3.af-south-1.amazonaws.com
#      - CIABPASSWORD=${CIABPASSWORD:-secretpassword}
#    links:
#      - postgres:postgres
#    ports:
#      - "80:8888"
#    volumes:
#      - ./notebooks:/notebooks
#      - ./products.csv:/products.csv
#    restart: always

  checkdb:
    image: schaffdev/port_check:latest
    environment:
      - CHECK_HOST=postgres
      - CHECK_PORT=5432
    links:
      - postgres:postgres
